package eu.profinit.manta.connector.streamsets.model.model.stage;

import java.util.List;

/**
 * StreamSets Stage defines object that has input and output(includes event) lanes.
 *
 * @author mburdel
 */

public interface IStage {

    /**
     *
     * @return default name generated by StreamSets
     */
    String getInstanceName();

    /**
     *
     * @return name for specific Stage
     */
    String getStageName();

    /**
     *
     * @return UI Info contains label(defined name by user) and stage type
     */
    IStageUIInfo getStageUIInfo();

    /**
     *
     * @return lanes' Ids that are going to Stage
     */
    List<String> getInputLanes();

    /**
     *
     * @return lanes' Ids that are going from Stage
     */
    List<String> getOutputLanes();

    /**
     * Data flows through this lane are defined by generated events.
     *
     * @return lanes' Ids that are going from Stage
     */
    List<String> getEventLanes();
}
